### ISSUE TITLE
Add a way to include wheels not from PyPI

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#107]
E.g. locally built wheels, or from Gohlke's site (see #106).

I want to think about this a bit, because I want building to be as easy and consistent as possible, and if you have to build/download wheels and put them in the right place beforehand, it adds a couple more steps to the process. Then again, it's no worse than using the existing pynsist_pkgs mechanism.

**Comment by Siecje** [comment]
One option is to allow wheels to be placed in `pynsist_pkgs` without having to extract them.

**Comment by takluyver** [comment]
It is, but I think it's sometimes quite useful that the contents of `pynsist_pkgs` are copied to the `pkgs` directory of the install unmodified. So if I was going to do that, I'd probably look for a separate directory like `pynsist_whls` instead.

Another option would be to have an explicit lists of paths/URLs in the config file.

Another option would be to specify a directory, either in the config file or the command line, which would be searched for named wheels before PyPI, akin to the `--find-links` option for `pip install`.

**Comment by takluyver** [comment]
I'm currently leaning towards the last option I mentioned: a way to specify list of directories or URLs that Pynsist would search for wheels before looking on PyPI.

**Comment by flutefreak7** [comment]
Sorry to jump in ignorantly, but if I have something installed in my Python environment like Shapely installed from a wheel from Gohlke's site, and I want to include Shapely in my application, so I identify it in my cfg file... does pynsist grab the files currently in my install or will it try to grab a wheel from pypi? My current setup requires stuff from many places (pypi, anaconda, conda forge, Gohlke's site, PySide website, GitHub, etc). Basically I'm confused by the topic since I didn't realize it dealt with wheels or cared where they came from.

**Comment by flutefreak7** [comment]
I just read issue #30 about OpenCV, and I think I understand now. Pynsist will grab the folder from site-packages, but could miss DLLs (a very common problem), so rather than telling the install script to include them all explicitly, you're counting on wheels to already contain everything you need. Then the installer smartly installs any included wheels into the application directory using pip?

**Comment by takluyver** [comment]
Yep, that's about how it works. The list you specify as `packages` must be importable module names, which it will find already installed on your system and copy into the installer. The list specified as `pypi_wheels` will be downloaded from PyPI and unpacked (not actually using pip, but the effect is similar). You can also put extra packages (as importable files and directories, not wheels) in a folder called `pynsist_pkgs` next to the config file; Pynsist will copy them in.

This issue is about adding a mechanism to get wheel files from a source other than PyPI.

**Comment by albertogomcas** [comment]
I am currently using the suggested workaround (extract all wheels to pynsist_pkgs) which works but is rather "unclean" for version control whenever a wheel is updated. 

It would be great if pynsist would also look into for example pynsist_wheels and extract any wheel found there into the build.

**Comment by takluyver** [comment]
Pynsist 2 - which was just released - allows you to specify local directories containing wheels:

```ini
[Include]
pypi_wheels = foo==1.5
extra_wheel_sources = pynsist_whls/
```

In this example, you'd have a directory `pynsist_whls` next to the config file, containing e.g. `foo-1.5-py3-none-any.whl`.

For now, it only works with local directories, to keep things simple. We could add support for URLs, like pip does, if people want it, but it would make caching more complex.
