### ISSUE TITLE
Support for offline usage

### ISSUE THREAD

**Issue by wlongxiang** [takluyver/pynsist#135]
I am working on a python project in an isolated network, so no connection to internet is allowed. But when using pynsist, it tries to fetch a embedded python from https://www.python.org/ftp/python. This does not work for me because the url seems to be hardcoded. Is there any fix or new requirement planned for this?

**Comment by takluyver** [comment]
I haven't got any immediate plans to change that. I hadn't really
considered offline use - sorry. If you can figure out from the code the
cache location that it stores Python in after downloading it, you can put
the file there manually, and then it will use that rather than trying to
download it.

**Comment by takluyver** [comment]
I'm going to close this because I still don't have any plans to support it explicitly. See the docs page on why I say no to features and what you can do instead:

https://pynsist.readthedocs.io/en/latest/design.html

In particular, if you wanted to reuse Pynsist's code for this, you can probably do it by changing or overriding one method, `fetch_python_embeddable`:

https://github.com/takluyver/pynsist/blob/b066fabf3d8b31e8d8980d383992a0f5b3de6124/nsist/__init__.py#L180-L212
