### ISSUE TITLE
Support sdist and egg formats

### ISSUE THREAD

**Issue by zuckerruebe** [takluyver/pynsist#211]
This has probably been asked before somewhere, but I couldn't find an answer browsing through the issues.

Is there any compelling reason to only support wheels (and not sdist and egg) packages? Or has it just not (yet) been done?

Out of interest: doesn't pynsist just use pip & friends internally so support for all of pip's supported package formats is "automatic"?

Thanks,
Damian

**Comment by takluyver** [comment]
Not supporting sdists is about keeping things simple: wheels can just be unzipped into the correct directory and you're done. Sdists have to be built, which involves executing code from the package and may do all sorts of things. In particular, one of the key advantages of Pynsist is that you can build a Windows installer from Linux or Mac. But Python has no general support for cross-compiling packages, so if I used an sdist of a package with extension modules, e.g. Pyzmq or NumPy, it would compile Linux libraries rather than Windows libraries.

In principle, we could support sdists for simple cases, where the package is just Python code & static data files. But there's no easy way to detect if a given package is simple or not, so we couldn't give a nice error message to explain that limitation. So it's easier to say that if you need to use something simple which is only published as an sdist, you should make a wheel (`pip wheel foo`) and give it to Pynsist.

Eggs won't happen - that's an old format which has been replaced by wheels. Pip doesn't support eggs either, as far as I know.

> doesn't pynsist just use pip & friends internally so support for all of pip's supported package formats is "automatic"?

It doesn't - it implements its own logic to identify and unpack wheels, which you can see here: https://github.com/takluyver/pynsist/blob/master/nsist/wheels.py

I think when I made this, you couldn't tell pip to fetch a wheel for a different platform (e.g. a Windows wheel when you're on Linux). Now you can with the `--platform` option. But this is also partly a vague principle: don't push out too much complexity to dependencies. Pip is a complicated, fast moving project, and if Pynsist used it in a slightly odd way, each new pip release might change how Pynsist behaves. Implementing similar functionality in Pynsist means some duplicated effort, but then much more stability. If there is an issue, it's more likely a simple bug in my code which I can see and fix, rather than a messy compatibility problem across two different codebases.

Anyway, maybe that was a longer answer than you were hoping for, but it distracted me from doomscrolling for a few minutes. :slightly_smiling_face:

**Comment by zuckerruebe** [comment]
Haha, whatever the reason, I'm grateful for the long answer. And I didn't know about ``pip wheel foo``. Thanks for that!
