### ISSUE TITLE
Pynsist Streamlit Exe application not working in Windows 10?

### ISSUE THREAD

**Issue by RizwanMunawar** [takluyver/pynsist#252]
I have followed all the steps mentioned in the repository to convert my streamlit webpage to executable. When I install the application, it throws an error as mentioned below.
**"localhost refused to connect."**
I have tried multiple times, but it's not working.

My Folder Structure:

 src
 ---> run_app.py
 ---> maincode.py
 ---> other folders

installer.cfg
I have added a folder path inside the config file as mentioned below.
---->files=src/foldera
------------->src/filea

**Comment by takluyver** [comment]
I know very little about Streamlit; @mattiatantardini might have more ideas. But I would guess the streamlit server is failing to start, so there's nothing to connect to. There might be useful error messages in the log file (see https://pynsist.readthedocs.io/en/latest/installers.html#logging-output )

**Comment by mattiatantardini** [comment]
Hi @RizwanMunawar, is this an error reported by streamlit that you can see in the logs? If so, can you provide the full traceback?

As a general suggestion, I also advise you to check the streamlit version that you are using. It is passed some month since I pushed the example and many new streamlit versions have been released, so there may also be some missing dependency that needs to be inserted in the `installer.cfg`.

**Comment by RizwanMunawar** [comment]
Thanks @mattiatantardini @takluyver, I have read your valuable answers. Definately, your provided guidence will help to understand the issues and debugging in code. Yes, the major issue I was facing is that I was not able to find error logs, but now I am able to get that. Now hopefully I will be able to resolve the issues.
