### ISSUE TITLE
install for all users if installler is run with admin privilegs

### ISSUE THREAD

**Issue by franzhaas** [takluyver/pynsist#258]
Dear all,

I ended up copying the nsis template and removed 1 line.:

!define MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER

Is there a more convenient way to do that?

Thanks in advance,
Franz

**Comment by takluyver** [comment]
Hi Franz,

When you say 'with admin privileges', do you mean you're logged in as a user with admin rights, or are you doing something extra, like right-clicking and selecting run as admin. I think when I wrote this (years ago), I was aiming for it to do user installs by default for all users, even if they had admin access. But I haven't actually used Windows day-to-day since the XP era, so I'm pretty out of touch with how things behave nowadays.

**Comment by franzhaas** [comment]
Hi takluyver,

I have 2 use cases.

1.) i run a tool provided by our IT which creates a temporary user with admin rights and allows me to run a terminal as this user.
    - choco installs into that temporary user's home directory, which gets removed at next reboot.
 2.) I run the cmd with right click run as administrator

in both cases, I would like to have it installed system-wide.

Thanks for looking into this,
Franz

**Comment by takluyver** [comment]
So are you running the installer from the command prompt in 'silent' mode (without the UI)? It looks like the [multiuser support](https://nsis.sourceforge.io/Docs/MultiUser/Readme.html) has command line options `/AllUsers` or `/CurrentUser` to select one or the other - does that help?

**Comment by franzhaas** [comment]
Hi takluyver,

amazing.... this works!

Thanks a lot!
Franz

**Comment by takluyver** [comment]
No problem, glad it helped!

Do you think Pynsist should change the default behaviour? I'm still not quite sure how admin permissions work on Windows or what's common for other installers. :slightly_smiling_face:

**Comment by franzhaas** [comment]
I am sorry, I have no idea.
