### ISSUE TITLE
Python section: minimum Python version '>=' instead of '='

### ISSUE THREAD

**Issue by cachitas** [takluyver/pynsist#49]
Is it possible to define in the configure file a minimum version?
This way if the target machine already has a supported python version, installing another would not be necessary.

I tried this but seems that the parser does not support it. Only '=' worked.

**Comment by takluyver** [comment]
No, there isn't currently a way to do that. I'll leave this open as a feature request, but it's not a very high priority for me, because:

1. Installed size doesn't matter much - hard drive space is cheap, at least on the scale of the 10s of MB a Python installation takes.
2. That would need added complexity in the installer to work out if a compatible Python is already installed, rather than just running the Python installer and letting it work it out. Installer logic is harder to write and test, so I try to keep the complexity in the Python code that prepares the installer as much as possible.
3. I'm actually planning to move in the direction of bundling Python inside the application directory, rather than installing it globally, after discussions with people at Microsoft. Python 3.5 will have a new 'embeddable' Windows build which doesn't need to be installed.

**Comment by cachitas** [comment]
I got this idea because of how pip works, but your arguments are reasonable, thank you for the clarification. I also took a look at what Python 3.5 will bring, looks promising.

Another thing, I added the Python section because I needed to specify the bitness. It forced me to also specify the version. Couldn't it just use the last stable version as default? Just another suggestion.

**Comment by takluyver** [comment]
It actually does default to the version of Python that it's running in. It's just marked as required in the code to read the config file. I think it was required at some point in the past. Do you want to make a pull request to fix that?

**Comment by cachitas** [comment]
Yea I can try that. Still getting along with Github, it would be my first PR :)

**Comment by takluyver** [comment]
Thanks! Feel free to ask if you get stuck.

**Comment by takluyver** [comment]
@cachitas are you still interested in making a PR? I can fix it if you're not, but it might be useful practice if you want to get more familiar with Github. :-)

**Comment by cachitas** [comment]
Yes! This is on my To Do list but I am quite busy now. If this is not an urgent matter, I would ask you to wait for me to try it.

**Comment by takluyver** [comment]
It's not urgent, I just wanted to check you hadn't forgotten.

**Comment by takluyver** [comment]
I'm closing this now as, on reflection, I think specifying an exact Python version is preferable: it makes it clear which version of Python is built into the installer, for instance if you want to work out 'what version of Python was uar 0.3 built with', it's right there in version control. (Yes, I looked up your project for the example ;-)

I've also recently added support for fetching wheels from PyPI to include in the installer, and these also require an exact version to be specified, for similar reasons.

**Comment by cachitas** [comment]
All valid reasons. Keep up the good work!

**Comment by takluyver** [comment]
Thanks Hugo! :-)
