### ISSUE TITLE
New release or git version should be installable with pip

### ISSUE THREAD

**Issue by raphaelm** [takluyver/pynsist#51]
Hi, it's been a while since the last release and a few bugfixes have been made since then, so I'd love to use the current version. However, 
``pip install -e git+https://github.com/takluyver/pynsist.git@master#egg=pynsist``
 does not work, as there is no ``setup.py`` file in the respository. I could clone it manually and run ``flit install``, but I can't do this in my requirements.txt file automatically for my coworkers and in every new virtualenv. Would it be an option to create a setup.py file that just calls ``flit install``?

**Comment by takluyver** [comment]
Thanks for the reminder. I'm currently in the middle of adding some features to support the embeddable Python builds coming with Python 3.5; once that's done, I'll cut a new release.

I don't want to add a setup.py to the repository, because I'd rather not have to field the inevitable questions about why it isn't a normal setup.py, why it doesn't behave like a normal setup.py, and so on.
