### ISSUE TITLE
PYGI example on the documentation doesn't gather all dependencies.

### ISSUE THREAD

**Issue by xor** [takluyver/pynsist#52]
I followed all the instructions on the example you have on the documentation to build an installer for a GTK application using Python 3.4, and GI, on a 64 bit system using Fedora.

https://github.com/takluyver/pynsist/tree/master/examples/pygi_mpl_numpy

When I tried running it on a Windows 10 64 bits VM I got an error importing GTK. I tried manually installing PYGI and Python instead, and the application worked fine. So I took a look at the extract.sh script, and there is a dependency missing. HarfBuzz, which was made into an independent package on rev20 of PYGI. So I added that dependency to the array variable on the extract.sh script, and all was well.

**Comment by tobias47n9e** [comment]
Hi @xor! Thanks for posting this! I made that example a while back, but I could only test it on W7.

Do you want to update the example, or should I do it? I also noticed that they already published rev21 yesterday on Sourceforge (http://sourceforge.net/projects/pygobjectwin32/files/).

**Comment by xor** [comment]
I prefer you update the example.

The reason this behavior was triggered is that I changed my download.sh script to get a more recent version of pygi, rev20, rev21 doesn't seem to have any big changes, so it should work as well.

**Comment by takluyver** [comment]
Thanks for letting us know. Just to check: you mean that HarfBuzz has become a dependency of one of the other GTK bits - not just that it's a dependency for your application. Right?

If you can tell us, what's the application you're using Pynsist for? It doesn't matter for this bug, but I'm interested to know what people are doing with the tool.

@tobias47n9e thanks for staying around to respond to things like this. If you've got time to update the example to use the latest pygi bundle, that would be great - and even better if you can test it as well, since I don't have easy access to a Windows machine at the moment.

**Comment by tobias47n9e** [comment]
@takluyver: I am glad I can help out a little bit. Pynsist is such a awesome tool for Windows packaging.

HarfBuzz is indeed a new package in the pygi-folder. But it just means that the array in the shellscript has one more entry:

     array=( ATK Base GDK GDKPixbuf GTK HarfBuzz JPEG Pango WebP TIFF )

I will just still run a couple of tests and see if everything works on W7.

**Comment by xor** [comment]
@takluyver 
>Thanks for letting us know. Just to check: you mean that HarfBuzz has become a dependency of one of the other GTK bits - not just that it's a dependency for your application. Right?

Right. HarfBuzz is a dependency of Pango, which is a dependency of GTK. The way I understand it, the code was already in Pango, but was made into an independent package on pygi rev20, so now it has to be explicitly included.

**Comment by takluyver** [comment]
Great, thanks. @tobias47n9e has updated the example in #53, which I just merged.
