### ISSUE TITLE
Install command line launchers

### ISSUE THREAD

**Issue by takluyver** [takluyver/pynsist#61]
Ping @davvid and @paulproteus who have asked for this feature, and @glyph, who is interested.

@pfmoore's [notes on making Windows commands](http://paul-moores-notes.readthedocs.io/en/latest/wrappers.html) are pretty clear that making an exe launcher is the only way to offer a command that doesn't have surprising traps lurking. As such, I would use either his [shimmy](https://github.com/pfmoore/shimmy) project, or the [cli launchers](https://github.com/takluyver/win_cli_launchers) pulled out of setuptools - which are less flexible, but more battle tested.

I envisage an interface something like this:

```ini
[Command foo]
entry_point=foomod:main
```

Using a section per command, rather than `foo=foomod:main`, leaves room for other parameters to be added. With shimmy, we could also support an arbitrary command with `target` and `parameters` options (like shortcuts already allow). With the setuptools cli launchers, we're limited to Python code.

The stub exes are a few tens of KB, so installer size shouldn't be a concern. The actual Python code is run as a subprocess, not the main process you start - but for most purposes it doesn't matter, and that's already the case with Python's `console_scripts`  entry points.

Do we shove the exes somewhere that's already on `%PATH%`, or install them as part of the application and add a directory to `%PATH%`? I'm leaning towards the latter.

**Comment by davvid** [comment]
This sounds like the right way to go all around. I understand that the way we have a raw launcher script is kind of frowned upon in the python world, so I think it might be okay to eventually move to installing the modules in site-packages (as desired in #181) so that we can be more like a regular python package.

It would be really nice to still be able to run out of the source tree (without having to do `python setup.py develop`) as described in the readme; I'm guessing we'll need to adjust how we find icons and paths relative to the package. Not sure if pkg_resources would solve that problem for us if we mark it as a non-zip-safe package, but it doesn't seem unsurmountable.

Fixing just the Windows issues first is fine too, I just figured I'd mention that issue since it's somewhat related.  Whenever I think about addressing it I'm always dissuaded because I don't want to make more work for packagers (we'd be breaking all the existing rpm, deb, and possibly other packaging by changing our filesystem layout). OTOH, by making the packaging more mainstream we're also making things simpler for packagers in general since it'll be just like any other python app.

I think your idea about installing the exe's as part of the app and adding the directory to `%PATH` sounds like a good approach.

**Comment by takluyver** [comment]
I like having launcher scripts that just import and call a function - keeping as much code as possible in importable modules feels like the right design, it simplifies testing, and it's convenient for installation (I like to symlink packages I'm working on into `site-packages`).

For applications, however, I don't think the code needs to go in `site-packages`. Debian, for instance, often puts the launcher script and the application package together under `/usr/share`, and symlinks the script to `/usr/bin`. For packages that don't provide a public Python API, this gives the application access to its own code without making it easily importable for other Python code.

**Comment by takluyver** [comment]
http://nsis.sourceforge.net/Path_Manipulation :

> this code will replace paths rather than append if the existing path exceeds the maximum string length in the NSIS build ...

> Default maximum string length is 1024, see Special Builds for a 8192 max length.

> The problem occurs because the function ReadRegStr returns the same result if 'value is too long' and if 'value is not set'. 

:angry:

**Comment by paulproteus** [comment]
BTW​, I think there is a solution to this, which is:

def append_to_path(thing_to_append):
    original = ReadRegStr()
    appended = original + ":" + thing_to_append
    SetRegStr(appended)
    if (ReadRegStr() != appended):
        # Restore backup
        SetRegStr(original)


But I haven't dug into the problem in depth.

**Comment by paulproteus** [comment]
Oh, that page says it does have an alternative implementation, but I don't
know enough NSIS to understand it yet.​

**Comment by takluyver** [comment]
Yep, I think that's the answer - we just have to invoke Python to do it rather than modifying it from NSIS.

**Comment by takluyver** [comment]
I have made a start on this in the `commands` branch. I'm using the setuptools exe launchers for now, but I don't think they can handle unicode paths in the shebang (unicode beyond the system code page, I mean).

**Comment by takluyver** [comment]
See #62 for the implementation.

**Comment by takluyver** [comment]
Done in #62
