### ISSUE TITLE
Automated installer testing

### ISSUE THREAD

**Issue by techtonik** [takluyver/pynsist#69]
[SikuliX](https://sikulix-2014.readthedocs.io/en/latest/index.html) can help with automated testing, but it would probably require a separate repository as it may need a big amount of screenshots.

**Comment by takluyver** [comment]
Thanks for the pointer.

NSIS installers do have a [command line option](http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers) for silent mode, so testing the basics should be possible even without using fancy tools to simulate user interaction.

**Comment by takluyver** [comment]
I've closed this, perhaps somewhat eagerly, because the basics are now in place: a test that generates an installer, runs it in silent mode, and checks the resulting installation.

I have no particular plans to work on testing the installer interactivity with GUI automation (the kind of thing SikuliX does), but if anyone is interested enough to spend time on it, I'd be interested to see how it goes!
