### ISSUE TITLE
Multiple Executables

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#82]
Is it possible to create an installer that installs multiple executables?

**Comment by takluyver** [comment]
* For multiple *shortcuts*, use `Shortcut` sections in the config file: http://pynsist.readthedocs.io/en/latest/cfgfile.html#shortcut-sections
* For command line exe launchers, use `Command` sections: http://pynsist.readthedocs.io/en/latest/cfgfile.html#command-sections

**Comment by Siecje** [comment]
Okay I looked at having multiple Application ```entry_point```. Didn't notice Shortcuts. You can close this issue.

I tried to make a PR with that info near ```entry_points``` but couldn't figure out how to link in reST.

Well I've got you here. 
Creating a Command creates a nice .exe but it also has a command prompt window.

Is it possible to create a .exe instead of a the .pyw or in addition?

**Comment by takluyver** [comment]
For what purpose do you want an exe without a command prompt window? The only use case I've found where you really need an exe is for setting up commands to run in a command prompt. For launching GUI interfaces, the shortcuts seem to work just fine with `python.exe` and the `.pyw` files. So there's currently no way to make a GUI exe in Pynsist, because it's not something I feel is important.

**Comment by Siecje** [comment]
How would I create a shortcut in the install directory? I want something that I can double click to launch the application.

**Comment by takluyver** [comment]
Why would you want it in the install directory? Don't you launch applications from the start menu, or whatever it's called now?
