### ISSUE TITLE
Suggestion: pip install packages from within pynsist

### ISSUE THREAD

**Issue by ugoertz** [takluyver/pynsist#89]
Enhancement suggestion/question: It would be great to be able to install Python packages into the Python instance installed by pynsist (i.e., to run `pip install -U xyz` commands after running the Python installer).

This would allow to quickly produce a nice installer for packages which are deployed to PyPI anyway: It would install Python, the package (and its dependencies, relying on pip) and a shortcut in one go. Much simpler for the end user than installing Python first and typing some pip command, and on the other hand it would be easier for the developer dealing with package dependencies.

It also could be useful to just install some of the dependencies of some package, and having the package itself installed by pynsist in the usual way.

The only downsides I can think of are that the pip-installed packages would end up somewhere inside the Python folder and could not be easily uninstalled separately, and that things have to be downloaded (by pip) from PyPI during the installation. Neither seems a big problem in the scenarios I am thinking of.

Or am I missing a simple existing way of doing this?

Thanks for the great work so far, I really like the pynsist approach to deployment.

**Comment by takluyver** [comment]
To clarify, do you mean:

1. Allowing the end user to pip install packages into the Python set up by a Pynsist installer, or
2. The installer fetching and installing packages from PyPI when it's installing the application.

For 1: Pynsist is primarily designed around applications where the user never needs to know about what language it's written in. If it needs a mechanism to install plugins, I'd recommend providing a way for the user to do that inside the application. It wouldn't be impossible to expose pip, but it's further complicate by:

- There may be many copies of Python on one machine; you don't want `pip` to just point to whichever was used last.
- Applications installed systemwide (currently all applications - see #65) are not user writable, so you need a 'run as admin' command prompt to install anything to them.

For 2: I try to keep the installers as simple as possible, because they're awkward to test, and so I like to do more of the logic in the build step. The potential advantages of running pip at install time are automatic dependency resolution and having up to date versions of packages. However, you lose the predictability of knowing what packages and versions will be installed. You also lose the self-contained installer for offline use.

Pynsist could do some form of dependency resolution when building the installer. But my experience with freeze tools is that this is a lot of bother and still doesn't work terribly well. It shouldn't be too hard to simply list all the necessary packages to be bundled into the installer. So my preference is not to try to resolve dependencies.

If you want a tool to set up Python environments which the user can then install things into, have a look at [Conda constructor](https://github.com/conda/constructor).

**Comment by ugoertz** [comment]
Thanks for the quick reply! I am referring to

2. The installer fetching and installing packages from PyPI when it's installing the application,

and I still think that this would be a nice addition. As you point out, using `pip install -U` would even allow to use the very same installer file for different versions of a program, and also for installing updates.

As to losing predictability: Since pip also allows fixing the version number, I do not see a real problem there. It is true that this would not be adequate for offline use, but I think that for most applications this is not an issue - the installer itself will be obtained via the net almost always, I think.

I agree that having pynsist do the resolution of dependencies might not be the right path. I certainly agree that the currently available freeze tools are kind of painful to use (even though a lot of work has been put into them and I ended up with PyInstaller in my current use case).

It is very understandable that you are hesitating to overload pynsist with further functionality, but wouldn't this thing be very much in line with the pynsist philosophy: Python is installed in the "correct" way, further packages would be installed by pip in the "correct" way, letting pip take care of dependencies. In case that all packages (including the application itself) are available on PyPI, pynsist would only have to install Python, run pip, and install shortcuts - seems very clean to me (and would be very useful to have, at least for me).

I also have the impression that it would be easy to add to pynsist (find the pip for the Python installation pynsist ends up with and run it by os.system calls or something similar) - but I did not think about it seriously, so I might be wrong.

**Comment by takluyver** [comment]
> As you point out, using pip install -U would even allow to use the very same installer file for different versions of a program, and also for installing updates.

It's an interesting possibility - build one installer and have it install the latest version of the program when it runs. But I think it goes against the general expectation that an installer is for a specific version of your program.

> Since pip also allows fixing the version number, I do not see a real problem there.

You could definitely do it with fixed versions of packages installed by pip. But if you're specifying the versions anyway, I think it's much better to download them at build time and bundle them into the installer itself, as Pynsist already does:

1. It moves potential failures from the user running the installer to the developer building it, who has a much better chance of understanding what's going wrong and fixing it.
2. It's much easier to test and debug the build code than the installer code. Python is a nice language, while NSI scripts offer a "lovely coding experience with elements of PHP and assembly." That's a real quote from the [features list](http://nsis.sourceforge.net/Features). ;-)

For these two reasons, I try quite hard to keep the installers as simple as possible.

If the motivation is mostly to pull in dependencies automatically, then I think there are a range of improvements we could make on the build side. I'm wary of automatically finding unspecified dependencies, because you can get different code depending on when you build the installer. But maybe a separate tool could examine the config file and add dependencies it discovered to the list of wheels to include.

We could also improve the support for pulling in packages, to support local wheel files and/or PyPI packages which don't have wheels yet (so long as we don't need to compile extension modules for them).

> I also have the impression that it would be easy to add to pynsist

Easy-ish. You have to make sure that pip is present, and work out where it needs to install to. You'd probably want to report at least some kinds of failure to the user in a comprehensible way (e.g. *no network access*). There are security concerns if it's going to download and execute code off the internet. It's doable, but not trivial.

So I'm still not sold on adding this to Pynsist. But if you want to go that way, then I'd encourage you to use the Pynsist code as a starting point, pull it apart a bit and make it do what you want. It may even be possible to do this in Pynsist with a custom template; the template inheritance system is pretty powerful.

**Comment by ugoertz** [comment]
Thanks for the explanations. Probably it is less straight-forward than I thought. I might give it a shot, but I am not sure when I will get around to doing it. Closing this for now.
