### ISSUE TITLE
32-bit QML Application not working on Windows 7

### ISSUE THREAD

**Issue by Siecje** [takluyver/pynsist#90]
I created an installer using the code from https://github.com/siecje/qml-testing/tree/pynsist with the ```bitness=32``` in ```installer.cfg```

I installed it on the IE8 on Win7 machine from here

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

When I launch the shortcut nothing happens. If I run it from Python 

```shell
> Python\pythonw.exe QMLApplication.launch.pyw
```

In `%appdata%\QMLApplication.launch.pyw`

there is

```
Traceback (most recent call last):
  File "QMLApplication.launch.pyw", line 30, in <module>
    from qmlapp import Main
  File "pkgs\qmlapp\__init__.py", line 1, in <module>
    from .main import Main
  File "pkgs\qmlapp\main.py", line 5, in <module>
    from PyQt5 import QtCore, QtGui, QtQml
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by takluyver** [comment]
(Aside: in the command line, you can run with `python.exe` instead of `pythonw.exe` to get tracebacks directly in the command prompt)

Can you try:

1. Split that import statement out into separate lines so we can see which module is actually causing the problem.
2. Use [dependency walker](http://www.dependencywalker.com/) on the .pyd file having the problem, and see if you can work out what DLL is missing.

**Comment by Siecje** [comment]
Okay I was wondering why I wasn't getting output in the console.

All of the imports fail with the same message. It just depends which one it tries first.

I opened ```C:\Program Files\QMLApplication\Pkgs\PyQt5\QtCore.pyd``` in ```Dependency Walker```.

It said it was missing some `.dll` files, but some of them were in the Python directory. I added `C:\Program Files\QMLApplication\Python\` to the search path.

It says it is missing

```
Qt5Core.dll
IEShims.dll
```

Note: `IEShims.dll` was not present before adding the Python directory to the search path.

**Comment by takluyver** [comment]
`IEShims.dll` can [apparently](http://www.qtcentre.org/threads/53275-Qt-5-Dependency-Walker-and-32-64-bit-dll) be safely ignored.

`Qt5Core.dll` is there under `PyQt5/Qt/bin/Qt5Core.dll`. The `__init__.py` modifies PATH to add that directory so that it can find those DLLs. Maybe something's going wrong with that PATH modification mechanism - but you already had this working with 64-bit Python, right? Both wheels use the same mechanism.

Maybe it's something further along. Does loading `Qt5Core.dll` in dependency walker show anything interesting?

**Comment by Siecje** [comment]
When I open `PyQt5/Qt/bin/Qt5Core.dll` and add `PyQt5/Qt/bin/Qt5Core.dll` as a search path the only missing modules are

```
CONCRT140.DLL
IESHIMS.DLL
```

**Comment by takluyver** [comment]
`CONCRT140.dll` sounds like yet another part of the MSVC runtime, which is gradually becoming Pynsist's nemesis. The PyQt5 wheels include `msvcp140.dll`, which I believe is the C++ part of the runtime, but neither PyQt5 nor the Python embeddable build appears to include `CONCRT140`.

@zooba, sorry to bother you again, but what is `CONCRT`, is it likely to be required for a PyQt5 application, and where should it be coming from?

The log messages don't mean much to me, but I don't know this stuff well.

**Comment by Siecje** [comment]
For the record I have not tested the 64bit installer on a fresh 64bit Windows installation.
I found the IE test VMs and the first one I downloaded for IE 8 was 32bit and decided to test there.

I found this https://msdn.microsoft.com/en-us/library/ee207192.aspx#runtime

I'm not sure if it is related but it says some of the functionality has been replaced by `Windows ThreadPool` and the application does use the Python `threading` module.

**Comment by takluyver** [comment]
Aha, CONCRT = concurrency runtime. I doubt it's related to Python's threading support, but I wouldn't be surprised if Qt uses it.

In your Windows installation where this is failing, can you install Python 3.5, `pip install PyQt5` into it, and see if you can import `PyQt5.QtCore` there? If that fails as well, then it may be something that Riverbank is missing when making the wheels.

**Comment by Siecje** [comment]
Oddly I tried to install Python 3.5.2 32bit and it got stuck on

```
installing C Runtime Update (KB2999226)
```

It was stuck for about an hour and `svchost.exe` had 100% CPU and 800 MB RAM.

The install log contained

```
#...
[0C8C:0EE4][2016-11-18T10:43:14]i305: Verified acquired payload: path_JustForMe at path: C:\Users\IEUser\AppData\Local\Package Cache\.unverified\path_JustForMe, moving to: C:\Users\IEUser\AppData\Local\Package Cache\{7E08C4EE-B1C7-4138-8227-7CD3837636AA}v3.5.2150.0\path.msi.
[0D24:0C28][2016-11-18T11:21:02]e000: Error 0x80070642: Bootstrapper application aborted during MSU progress.
[0D24:0C28][2016-11-18T11:21:02]e000: Error 0x80070642: Failed to execute MSU package.
[0C8C:0668][2016-11-18T11:21:02]e000: Error 0x80070642: Failed to configure per-machine MSU package.
[0C8C:0668][2016-11-18T11:21:02]i319: Applied execute package: crt_14.0_v6.1_x86, result: 0x80070642, restart: None
[0C8C:0668][2016-11-18T11:21:02]e000: Error 0x80070642: Failed to execute MSU package.
[0D24:0C28][2016-11-18T11:21:02]i351: Removing cached package: crt_14.0_v6.1_x86, from path: C:\ProgramData\Package Cache\D4036846864773E3D647F421DFE7F6CA536E307B\
[0C8C:0668][2016-11-18T11:21:02]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{cf72a2ab-2f1d-49fd-a0d7-1065e6357e1e}, resume: None, restart: None, disable resume: No
[0C8C:0668][2016-11-18T11:21:02]i330: Removed bundle dependency provider: {cf72a2ab-2f1d-49fd-a0d7-1065e6357e1e}
[0C8C:0668][2016-11-18T11:21:02]i352: Removing cached bundle: {cf72a2ab-2f1d-49fd-a0d7-1065e6357e1e}, from path: C:\Users\IEUser\AppData\Local\Package Cache\{cf72a2ab-2f1d-49fd-a0d7-1065e6357e1e}\
[0C8C:0668][2016-11-18T11:21:02]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{cf72a2ab-2f1d-49fd-a0d7-1065e6357e1e}, resume: None, restart initiated: No, disable resume: No
[0C8C:0668][2016-11-18T11:21:02]i399: Apply complete, result: 0x80070642, restart: None, ba requested restart:  No

```

Then I reverted the VM to the same snapshot and tried again and it installed without any problems.

When I run `python` I get an error window that says

```
The program can't start because api-ms-win-crt-runtime-L1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.
```

I have tried reverting to the first snapshot (fresh download of the VM) and I get the same thing.

**Comment by Siecje** [comment]
Nevermind the above.

That was because the copy of Windows was not activated and it was trying to use Windows Update

**Comment by Siecje** [comment]
Okay so apparently the Python 3.5.x installers only work out of the box on Window 10+

I had to install the Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026

in order to just run `python`

After that I was able to `python -m ensurepip` and `pip3 install PyQt5`

I was able to import 

```
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtQml
```

**Comment by Siecje** [comment]
After installing `Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026`

`CONCRT140.dll` is located in `C:\Windows\System32\`

So does `Pynsist` need to include the `CONCRT140.dll` from the Visual C++ 2015 Redistributable

Downloads links https://www.microsoft.com/en-ca/download/details.aspx?id=48145

**Comment by zooba** [comment]
The Python 3.5 installers will install the required update on pre-Windows 10 machines. Windows 10 already includes the necessary files, so it doesn't need to do it.

CONCRT140.dll is part of the C++ runtime, which is not part of the C Runtime update that gets installed. Python does not depend on it, so PyQt5 should either include it or specify that you need to install the C++ redist to get it. Alternatively, whoever builds it could statically compile these DLLs into the PyQt5 binary.

That said, if pynsist starts installing the C++ runtime everywhere, installs will be bigger, take longer, require admin privileges, and be more likely to fail, but once you get past all that then you'll have both C and C++ runtimes and it won't matter what dependencies need. (Up until those dependencies switch to a new compiler version, and suddenly you need CONCRT141.dll or something - this is why I decided that Python will only include its own dependencies and packages should include their own or otherwise require them.)

**Comment by Siecje** [comment]
> The Python 3.5 installers will install the required update on pre-Windows 10 machines.

@zooba Any idea why I wasn't able to run `python` without installing the Visual C++ Runtime?

It was in my PATH and the error message even happened when I double clicked `python.exe`

**Comment by zooba** [comment]
@Siecje If you successfully installed it using the installer, then I'd need to see all your logs (`%TEMP%` directory).

If you used the embeddable ZIP file then you need to install the C runtime yourself - installing the C++ runtime is one way to get it. Installing all available Windows Updates is another way, as it was made available all the way back to Windows Vista via WU.

**Comment by Siecje** [comment]
@zooba I emailed you the logs with a full explanation of the steps.

Thanks a lot @zooba and @takluyver for helping me figure out what was going on. Thanks so much!!

**Comment by takluyver** [comment]
Thanks Steve,

> CONCRT140.dll is part of the C++ runtime, which is not part of the C Runtime update that gets installed. Python does not depend on it, so PyQt5 should either include it or specify that you need to install the C++ redist to get it.

PyQt5 already includes msvcp140, which I believe is part of the C++ runtime, in the Windows wheels. If it's already including one C++ runtime DLL, I'd guess it makes sense for it to include concrt140 as well? It might reach out to the PyQt developers about this.

To check my understanding: the [Visual C++ redistributable](https://www.microsoft.com/en-ca/download/details.aspx?id=48145) includes the C and C++ runtimes, right? I've been pointing people to this in the docs if they don't want to bundle the universal C runtime DLLs into their installer.

**Comment by zooba** [comment]
> To check my understanding: the Visual C++ redistributable includes the C and C++ runtimes, right?

That's right. The C runtime is a prerequisite for the C++ runtime, so it makes sure you have both. (Though if you're a Python 3.5+ extension, you can assume that the C runtime is already available.)

**Comment by takluyver** [comment]
Thanks @Siecje - I was just going to ask about including CONCRT140 in the PyQt5 wheels, but I see you've [already done it](https://www.riverbankcomputing.com/pipermail/pyqt/2016-November/038329.html). :-)

**Comment by Siecje** [comment]
There is a new version of PyQt5, version 5.7.1 which includes `CONCRT140.dll` in the wheel.

I've created a new 32-bit installer using this code

https://github.com/Siecje/qml-testing/tree/e2b71e13396c0a8cc9eafbc06fc502b953534e60

When I run the shortcut in the start menu, nothing happens, no error window or anything.

`%appdata%\QMLApplication.launch.pyw` contains

```
Traceback (most recent call last):
  File "C:\Program Files\QMLApplication\QMLApplication.launch.pyw", line 30, in <module>
    from qmlapp import Main
  File "C:\Program Files\QMLApplication\pkgs\qmlapp\__init__.py", line 1, in <module>
    from .main import Main
  File "C:\Program Files\QMLApplication\pkgs\qmlapp\main.py", line 5, in <module>
    from PyQt5 import QtCore
ImportError: DLL load failed: The specified module could not be found.
```

I have looked at the `QtCore.pyd` and `Qt5Core.dll` files in Dependency Walker but there doesn't seem to be anything missing.

Two of the dependencies have a red icon.

![dep](https://cloud.githubusercontent.com/assets/4069476/21621813/a7a542fc-d1c8-11e6-84bb-8173def556ed.PNG)

**Comment by takluyver** [comment]
That's puzzling. Is there any information in the UI on what the red icons mean? Does it work if you install Python and `pip install PyQt5` again?

**Comment by Siecje** [comment]
I can't figure out why those two files have a different icon.

When I install Python 3.6.0 or Python 3.5.2 on this VM I get an error about missing `api-ms-win-crt-runtime-L1-1-0.dll`

This is what I am doing:

1) I downloaded the VMWare VM for IE 8 on Win 7 from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
2) Activated Windows for 90 days by running `slmgr /ato` in a administrative command prompt (Just incase an invalid license would prevent a request for a Windows update to be installed)
3) Downloaded Python 3.6.0 installer https://www.python.org/ftp/python/3.6.0/python-3.6.0.exe
4) Run installer and checked add Python to PATH during install wizard
Install location is `C:\Users\IEUser\AppData\Local\Programs\Python\Python36-32` by default.
5) Open cmd.exe and run `python`
Get error window in the attached image.
6) Restart Windows
7) Open cmd.exe and run `python`
Get error window in the attached image.

![error](https://cloud.githubusercontent.com/assets/4069476/21720105/51af1aa2-d3ef-11e6-8496-e92d1068e4e0.PNG)

I have attached the Python logs found in `%temp%`

[Python 3.6.0 (32-bit)_20170106053853_logs.zip](https://github.com/takluyver/pynsist/files/690057/Python.3.6.0.32-bit._20170106053853_logs.zip)

**Comment by Siecje** [comment]
The same error happens when I download the embeddable zip file and extract it and run python.exe 

https://www.python.org/ftp/python/3.6.0/python-3.6.0-embed-win32.zip

**Comment by takluyver** [comment]
@zooba : the description @Siecje gives above sounds like the Python installers are failing to install the necessary bits of the CRT for Python itself. Is this something you're aware of already?

I don't think that should affect the Pynsist-built installer, though. That DLL should be packaged and installed in the `Python` subdirectory of the installation, since you're using the `bundled` format.

Apologies if I already asked about this, but is this specific to 32-bit? Does it work if you build an installer with 64-bit Python?

**Comment by Siecje** [comment]
I don't have a 64-bit Windows to test.

But I have discovered the problem. 

Python requires this Windows update https://support.microsoft.com/en-us/kb/2999226

I tried running `Windows Update` but it was talking a very long time. So I tried installing the update directly but it too was taking a long time, stuck at "Searching for updates on this computer..." 

By following the instructions here http://www.freenode-windows.org/resources/vista-7/windows-update

I was able to stop `Windows Update` and install that update directly. After that Python and the pynsist applications worked!!!

**Comment by takluyver** [comment]
That fits in with my understanding of why the Python installer doesn't work - it tries to install that update on your system, and evidently it's not working properly. But the Pynsist application shouldn't need that, as far as I know - it should bundle those libraries.

What version of Pynsist were you building with? if it's older than 1.9, can you upgrade and try again? I changed how the CRT is handled in 1.9.

**Comment by Siecje** [comment]
That was with version 1.9

The problem was that even the embeddable Python was not working.

Are you saying that `pynsist` will install the files that are found in this Windows Update? https://support.microsoft.com/en-us/kb/2999226

**Comment by takluyver** [comment]
Yep, it should install them if it doesn't find `ucrtbase.dll` already present on the system. Here they are in the package:

https://github.com/takluyver/pynsist/tree/master/nsist/msvcrt/x86

Can you look into the `Python` subdirectory under the install directory, and see whether they are installed?

**Comment by takluyver** [comment]
To clarify, I'd ideally like you to look in the install directory on a system where it's not working.

**Comment by Siecje** [comment]
Yes `ucrtbase.dll` is there

**Comment by takluyver** [comment]
So you can run that `python.exe` but it can't import PyQt5 without the update installed? That sounds to me like PyQt5 is still missing some DLL that it requires in that situation, like it was missing CONCRT before. I don't know how to find out what that is, though.

**Comment by Siecje** [comment]
What else does Window Update `KB2999226` do besides installing the files the installer is adding?

https://github.com/takluyver/pynsist/tree/310af49bb98a61ab0a9c1cd52a137453f559fcd5/nsist/msvcrt/x86

If I install the update the pynsist installed application works.

**Comment by Siecje** [comment]
According to the list of files for `KB2999226` on Windows 7 x86 here

https://support.microsoft.com/en-ca/kb/2999226

Under "For all supported x86-based versions of Windows 7"

The folder in the pynsist repo is missing 

https://github.com/takluyver/pynsist/tree/310af49bb98a61ab0a9c1cd52a137453f559fcd5/nsist/msvcrt/x86

```
api-ms-win-core-xstate-l2-1-0.dll
api-ms-win-eventing-provider-l1-1-0.dll
```

From fresh Windows 7 I install the pynsist application and then copy those two files into the Python sub directory of the install directory and it doesn't work.

Nothing happens when I launch the shortcut but the file in `%appdata%`

contains

```
Traceback (most recent call last):
  File "C:\Program Files\QMLApplication2\QMLApplication.launch.pyw", line 30, in <module>
    from qmlapp import Main
  File "C:\Program Files\QMLApplication2\pkgs\qmlapp\__init__.py", line 1, in <module>
    from .main import Main
  File "C:\Program Files\QMLApplication2\pkgs\qmlapp\main.py", line 5, in <module>
    from PyQt5 import QtCore
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by Siecje** [comment]
Maybe there are more files that are not listed on that page?

**Comment by takluyver** [comment]
Hmm, that's annoying. I probably got the files on my Windows 8.1 installation. I would have thought the SDK would include all the necessary ones, though.

But since copying them doesn't change things, it doesn't sound like they're the issue here.

**Comment by zooba** [comment]
I am aware of some issues where the update reports that it is installed, but it actually requires a reboot to finish installing. On a freshly created machine this is fairly likely, as it only really occurs when other updates have been installed and you haven't rebooted yet. The embedded distro is just as affected by this, as it requires you to manage the installation yourself rather than having the installer do it.

The only files included in that update should be `ucrtbase.dll` and `api-ms-win-crt-*.dll` files (`vcruntime140.dll` is included with Python, even the embeddable package). If they are `api-ms-win-(not crt)-*.dll` then they are system API sets that should be installed by the OS.

What may be happening here is the build is being done targeting a later version of the OS, and so when the PYD comes back to Win7 it is looking for files that are not guaranteed to be there. I'll need to look deeper into how this works, since (from memory) I'm not sure where those options would be, but it may just be the case that those also need to be redistributed with the build. If that's the case, they should be somewhere in a Redist directory on the machine that built it, and I'll have to look at making setuptools/distutils/wheel include them when necessary.

**Comment by Siecje** [comment]
Is it possible to see which files the update is adding?

The webpage lists `Api-ms-win-core-xstate-l2-1-0.dll` twice so maybe there is another file that gets installed?

**Comment by zooba** [comment]
Ah, I see. There are some extra files for Win8 and earlier in the KB that are not in the pynsist tree and not in the redist folder in the WinSDK. I'll ping the team that owns this so they can get the files added, but otherwise I'd suggest finding them on a Windows 7 or 8 (not 8.1) machine with KB2999226 installed and copying them from there.

**Comment by Siecje** [comment]
How do you find them?

**Comment by zooba** [comment]
They'll be in `C:\Windows\System32` for the 64-bit version and `C:\Windows\SysWOW64` for the 32-bit version (yes, I know the names are backwards).

I assume on Windows 8.1 and later the schema is embedded into the loader, so you'll only find the files on Windows 7 or 8 after installing that KB.

**Comment by takluyver** [comment]
Thanks @zooba. Can you ping me as and when the extra files are in the SDK, and I'll add them to Pynsist?

It sounds like the PyQt issue is something that needs to be fixed in the PyQt wheels. I don't know how to find out what file is missing.

**Comment by Siecje** [comment]
Is it possible to tell which files came from `KB1999116`?

After installing and looking in `C:\Windows\System32\` the only extra files that start with `api-ms-` are

```
api-ms-win-core-xstate-l2-1-0.dll
api-ms-win-eventing-provider-l1-1-0.dll
```

**Comment by zooba** [comment]
@Siecje The list of files is in the KB article which you posted earlier.

**Comment by Siecje** [comment]
Any idea why the application doesn't work until the KB is installed?

Even with all of the .dll files in a directory on the search path.

Does the update do anything else?

**Comment by zooba** [comment]
The issue was that not all the files were installed - the two that you listed above are missing from Pynsist because they are missing from the Windows SDK. 

The SDK team is going to fix their problem. The KB does not do anything other than copy the files into the right place.

**Comment by Siecje** [comment]
Those two files were installed into `C:\Windows\System32\` I copied them into the same directory that `pynsist` is putting them.

From a bare bones Windows 7 32-bit I installed the pynsist installer (which contains all but two of the api-ms-*.dll files) and then copied the two that were missing into the same location pynsist puts them.

And the application still doesn't work. But if I install the KB then it works. 

I'm trying to figure out why that is.

**Comment by takluyver** [comment]
Yeah, I don't understand how that collection of facts fits together... 😕

**Comment by zooba** [comment]
@Siecje Did you take the files from `C:\Windows\System32` on 64-bit Windows?

**Comment by Siecje** [comment]
No I took it from the same 32-bit Windows that it was working on.

I have a VM with snapshots and I installed the KB then copied the files out of the VM and then reverted to a snapshot before installing the KB and placed them in the Python directory in the pynsist directory.

**Comment by Siecje** [comment]
If I move the files from the Python directory to `C:\Windows\System32\` then it works.

Steps

1) Install pynsist installer
2) Application does not work
3) Copy `api-ms-*.dll` files from `C:\Program Files\QMLApplication2\Python` to `C:\Windows\System32`
4) Application now works.

This is without installing the KB.

**Comment by zooba** [comment]
Hmm... perhaps they need to be able to locate some other files in the system directory?

What is the error message you get with those files in the application directory? Or better yet, what does depends.exe say is missing?

**Comment by Siecje** [comment]
No error window or anything. `depends.exe` does not show anything missing.

In Python the error is about
```
from PyQt5 import QtCore
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by zooba** [comment]
depends always shows things missing - what file are you checking? I don't know the structure of PyQt5 off the top of my head, but I'd guess there's a qtcore.pyd somewhere that is the most interesting one to look at.

**Comment by Siecje** [comment]
Yes I have looked at it and added two search paths.

1) `C:\Program Files\QMLApplication\Python` (which is where pynsist puts the .dll files)
2) `C:\Program Files\QMLApplication\pkgs\PyQt5\Qt\bin`

It only shows `IESHIMS.DLL` as missing.
There is a different icon for some files, see the image in https://github.com/takluyver/pynsist/issues/90#issuecomment-270214918

**Comment by Siecje** [comment]
If I copy the `api-ms-*.dll` files from `C:\Program Files\QMLApplication\Python` to `C:\Program Files\QMLApplication\pkgs\PyQt5\Qt\bin` then it works.

Since those files are required by Python should `PyQt5` include the ones it needs?

Or is this a bug with `pynsist`?

**Comment by Siecje** [comment]
I got it to work!

I had to add this line in `QMLApplication.launch.pyw`

```Python
os.environ['PATH'] = os.environ['PATH'] + os.pathsep + os.path.join(scriptdir, 'Python')
```

One thing I noticed is that 'PYTHONPATH' is not in `os.environ`

**Comment by takluyver** [comment]
That's strange, because the [docs about finding DLLs](https://msdn.microsoft.com/en-us/library/7d83bc18.aspx) say that the first place it looks is "The directory where the executable module for the current process is located.", which should be the directory containing `Python.exe`.

@zooba do you have any idea why adding this directory to PATH should make a difference?

**Comment by zooba** [comment]
There are some ways to override the lookup order, but typically they exclude the (vulnerable) PATH variable rather than other mechanisms. Some [really complicated mechanisms](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374153(v=vs.85).aspx) can also "change" the base lookup directory when loading dependencies, but I'd be very surprised if QT is using this.

What may be more telling is to use depends.exe's profiling feature to run `python -c "import PyQt5.QtCore"` and see exactly which library is not being found and which one is trying to load it (caveat: I haven't successfully used the profiling feature in a few years, I suspect because it needs updating for Win8+).

Programmatically adding the prefix path using [AddDllDirectory](https://msdn.microsoft.com/en-us/library/windows/desktop/hh310513(v=vs.85).aspx) before importing is technically safer, but in this case not significantly safer than modifying PATH.

**Comment by Siecje** [comment]
It is strange, because `python.exe` requires the .dlls and it finds them, but when it tries to load `QtCore.pyd` it can't find it.

I will try Dependency Walkers profile feature.

**Comment by Siecje** [comment]
I can't seem to use the profile feature on Windows 7. It is greyed out.

I'm thinking this might be a problem with PyQt5, maybe it is changing the current directory with `os.chdir(path)`??

I'll try the mailing list.

**Comment by Siecje** [comment]
The `PyQt5==5.7.1` wheel is modifying the 'PATH' environment variable.

```
_path = _os.path.dirname(__file__) + '\\Qt\\bin;' + _os.environ['PATH']
_os.environ['PATH'] = _path
```

Is it possible to call `AddDllDirectory` from Python?

**Comment by Siecje** [comment]
Okay it also works if I pass the Python directory to `os.chdir(pythonDir)`

When I run the shortcut `os.getcwd()` is `C:\Users\IEUser` for the `IEUser` user. 



Inside `PyQt5/__init__.py`

I set 

```Python
print(_os.getcwd()) # C:\Users\IEUser
_os.chdir('C:\\Program Files\\QMLApplication2\\Python') # Application works
```

So maybe `os.chdir(os.path.join(installdir, 'Python'))` should be added to the launcher.pyw?

**Comment by takluyver** [comment]
Hmm, that's all a bit mysterious, but I'll trust you that it works. I like adding it to PATH better than changing the working directory.

**Comment by Siecje** [comment]
The same problem exists on Windows 8.1 32-bit. 

Adding 

```
os.environ['PATH'] += ';' + os.path.dirname(sys.executable)
```

in the launcher fixes it.

**Comment by zooba** [comment]
The UCRT team are suggesting to me that this may be an issue with an older UCRT version, and the latest (available in the latest WinSDK) should not have that dependency at all on any platform. So perhaps this can also be resolved by @takluyver updating the redist files in the pynsist repo?

**Comment by Siecje** [comment]
Which dependency?

**Comment by zooba** [comment]
The two DLLs that we had to copy from a separate installation.

**Comment by Siecje** [comment]
The two files that were in the KB for Win 7 but not in the pynsist repo? They didn't seem to be required. 

The real problem is that there are .dll files in the same directory as `python.exe`, and when python imports PyQt5.QtCore` it can't find the .dlls.

They should be found because it should check the directory the executable (python.exe) is in, but it doesn't seem to.

https://msdn.microsoft.com/en-us/library/7d83bc18.aspx

So by adding the directory that `python.exe` is in to either the 'PATH' environment variable or setting it to the current directory, the problem is fixed.

**Comment by Siecje** [comment]
I think

| 1. The directory where the executable module for the current process is located.

might mean the same directory as the file? So when the .dll file is not in the same as `python.exe` it doesn't check the directory the executable is in?

**Comment by Siecje** [comment]
We have 
```
<install_dir>\Python\python.exe
<install_dir>\Python\api-ms-*.dll

<install_dir>\pkgs\PyQt5\Qt\bin\QtCore.dll
```

`<install_dir>\Python\python.exe` is run and tries to  load
`<install_dir>\pkgs\PyQt5\Qt\bin\QtCore.dll`

there is a dependency on `api-ms-*.dll` and `<install_dir>\Python\api-ms-*.dll` is not found.

Adding `<install_dir>\Python\` to `PATH` is the current solution.

**Comment by zooba** [comment]
No, that definitely means the current process. But the right MSDN reference for how it is loaded is [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#alternate_search_order_for_desktop_applications) (we call [LoadLibraryEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179(v=vs.85).aspx) with (I believe) a fully qualified path and the `LOAD_WITH_ALTERED_SEARCH_PATH` option), where it says that the DLL directory is the one searched for dependencies.

So the end result is essentially that anything not already loaded into the Python process needs to be available to any extension that's being loaded. Prior to Windows 10, this means the API set DLLs (not ucrtbase.dll itself, which will be loaded already) need to be available either in the system directory (ideal), on the `SetDllDirectory` path (preferable) or on `PATH` itself.

Or possibly we need to support manually loading all of them on startup somehow (since Python itself does not "support" applocal CRT installs, it isn't really right to require it there, but loading all of those DLLs with ctypes before importing anything else might work).

**Comment by takluyver** [comment]
Aha, thanks for highlighting where the problem comes from. I don't know much about how compiled libraries are loaded, especially on Windows.

For the updated DLLs you mentioned, the SDK you're suggesting I need is the one available here, right?
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

So far, I think adding the directory to `PATH` is my preferred solution. It may not be very Windows-y, but we can easily do it from Python with a single line of code that I understand. That seems preferable to doing anything with ctypes.

**Comment by zooba** [comment]
That's the right SDK. Sounds like the update isn't immediately necessary, but it's going to be general goodness anyway (since you're responsible for making sure pynsist apps get their security fixes :) )

**Comment by Siecje** [comment]
I thought the files in https://github.com/takluyver/pynsist/tree/003a1e3e5a5133b80b010c1b6dbc536587ae0105/nsist/msvcrt are only needed on Windows < 10?

**Comment by zooba** [comment]
That's true. I don't understand the reason for the question.

**Comment by Siecje** [comment]
Just because that is a link for building apps for Windows 10. Windows 10 already comes with the files properly installed and able to be upgraded by Windows Update.

**Comment by zooba** [comment]
Ah, yeah. All the Windows SDKs are fully backwards compatible (with correct preprocessor definitions), so you can always use the latest available (though the SDK doesn't always work on the older operating systems, but it can still build for them).

**Comment by takluyver** [comment]
@zooba do you know if the missing files have been added to the SDK? I'm planning to do another release soon.

**Comment by zooba** [comment]
@takluyver I don't think we've released an SDK update recently anyway, so you'll have to acquire the extra files from a Win7 machine.

**Comment by davvid** [comment]
@takluyver I ran into similar issues when creating the git-cola installer from linux.  The target hosts were a win2008 server VM and a win2015 server VM.  Both failed to import sip and PyQt5 modules until I added an `extra_preamble` script:

https://github.com/git-cola/git-cola/blob/master/contrib/win32/pynsist-preamble.py

Until I did that, I was able to make things work by copying a whole bunch of the vcredist DLLs into the `pynsist_pkgs` directory, but then later I realized that I was just duplicating the same DLLs already present in the Python/ directory.  That got me to try adding both `Python/` and `pkgs/` to `$PATH` and that got cola working with the pypi-provided PyQt5+sip.

The target VMs are fresh installs, without any updates, in case that's a factor.

Does this seem like a decent solution?

If you think this tweak should be part of pynsist itself I'd be happy to put together a PR so that I don't have to carry around the preamble script.  Let me know what you think, and thanks again for pynsist.

**Comment by takluyver** [comment]
Adding the Python directory to the PATH seems a reasonable enough thing to do, although I thought the directory where the exe is located was already searched for loading DLLs. Having the pkgs directory on the PATH feels less clean, and I don't understand why it would be needed. :confused: DLL loading is a bit of a mystery to me.

**Comment by takluyver** [comment]
(But if putting pkgs on PATH is really the only way to make things work, I'll consider it)

**Comment by zooba** [comment]
@takluyver Depending on how far into the past you want to support, [AddDllDirectory](https://msdn.microsoft.com/en-us/library/hh310513.aspx) is a much better option than messing with `PATH` (and I have no idea why CSS is broken today on MSDN...)

**Comment by takluyver** [comment]
Thanks! I'd rather not mess with ctypes if I can avoid it, though.

**Comment by zooba** [comment]
cffi? :)

Or post a request on bugs.python.org to get it added to the winapi module. But that won't help before Python 3.8 at this stage.

**Comment by takluyver** [comment]
I mean, if `AddDllDirectory` is the way we need to go, it's one function with what appears to be a relatively simple API, so I'd probably use ctypes rather than adding another complex binary dependency for every app built with Pynsist. However:

- I'm not familiar enough with C programming or Windows to be confident calling a compiled function directly, whether with ctypes or cffi or Cython, or any other tool.
- I'd still like Pynsist to support installing on Windows 7 (it's still supported until 2020, and I know people still using it). It appears that it was added in an update for Windows 7, but I don't know if that update was pushed out automatically to all users or if there's a significant population who still don't have it.

**Comment by davvid** [comment]
In case it helps, I found this snippet which seems to be calling `AddDllDirectory` via ctypes:
http://codegists.com/snippet/python/mkl_dll_adddlldirectorypy_carlkl_python

**Comment by takluyver** [comment]
Thatnks, that might be useful if we do decide we need to use AddDllDirectory.
