### ISSUE TITLE
Shortcuts to websites?

### ISSUE THREAD

**Issue by Trilarion** [takluyver/pynsist#98]
Do shortcuts (start menu entries) to websites exist? How are they done or if not, could they be included in pynsist?

I imagine people would like to specify a homepage and putting additional links as shortcuts/entries into the application group in the start menu. From the logic this could be special shortcuts with special keywords.

**Comment by takluyver** [comment]
I believe they do exist, I'm not sure how they're done. If you look into it, let me know what you find.

It's possible (but unlikely, I think), that you can already make them by setting the `target` key of a shortcut section. At a pinch, you could probably set `target=iexplore` and `parameter=http://...`, but hardcoding IE isn't very nice. If it doesn't already work but it's possible to support in a clean way, I'd be open to adding that.

**Comment by Trilarion** [comment]
I'll look into it.

**Comment by takluyver** [comment]
FYI, from [this Microsoft help page](https://msdn.microsoft.com/en-us/library/windows/desktop/jj673981(v=vs.85).aspx), it looks like links to websites should be inside the app, not shortcuts in the start menu:

> DON'T: Don't put shortcuts to the following items on the Start screen:
> ...
> - Web sites. Provide any appropriate links to information like help and technical support sites directly in your app.

Also:

> DON'T: Don't create shortcuts to items that are not executable files. Shortcuts that don't map to executables, such as shortcuts that launch web sites or help files, are filtered out of the Start screen.

I haven't used Windows as my main OS since XP, when that kind of shortcut was normal, but it looks like Microsoft has tightened up what belongs on the start menu since then. So I'm going to close this.
